name: Build Test

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Add application-dev.yml file
      run: |
        echo "${{secrets.APPLICATION_DEV}}" > src/main/resources/application-dev.yml
      shell: bash

    - name: Add application-test.yml file
      run: |
        echo "${{secrets.APPLICATION_TEST}}" > src/test/resources/application-test.yml
      shell: bash

    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: clean build
