name: Push Docker Image

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ "main" ]

permissions:
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Add application-dev.yml file
        run: |
          cd ./src/main/resources
          touch ./application-dev.yml
          echo "${{secrets.APPLICATION_DEV}}" > ./application-dev.yml
        shell: bash

      - name: Add application-test.yml file
        run: |
          cd ./src/test
          mkdir resources
          cd ./resources
          touch ./application-test.yml
          echo "${{secrets.APPLICATION_TEST}}" > ./application-test.yml
        shell: bash

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean build

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKER_REPO}}:latest

      - name: Executing Remote SSH commands Using Password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            sudo docker rm -f $(docker ps -qa)
            sudo docker pull ${{ secrets.DOCKER_REPO }}
            docker run -itd -p 8080:8080 ${{ secrets.DOCKER_REPO }}
